In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
d1 = {
    "ages": [10,20,30,40]
}

In [4]:
s1 = pd.Series(d1)
print(s1)

ages    [10, 20, 30, 40]
dtype: object

In [5]:
type(s1)

pandas.Series

In [6]:
d2 = {
    "name":["vishwas","bob","john"],
    "city":["bangalore", "pune","delhi"],
    "salary":[20000,40000,30000]
}

In [7]:
df = pd.DataFrame(d2)
df.head()

      name       city  salary
0  vishwas  bangalore   20000
1      bob       pune   40000
2     john      delhi   30000

In [8]:
d3 = {
    "name":["vishwas","bob","john", "Rita","Smith"],
    "city":["bangalore", None,"delhi","kashmir",None],
    "salary":[20000,np.nan,30000,"20000",None]
}

In [10]:
df = pd.DataFrame(d3)
df.head()

      name       city salary
0  vishwas  bangalore  20000
1      bob        NaN    NaN
2     john      delhi  30000
3     Rita    kashmir  20000
4    Smith        NaN   None

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   city    3 non-null      str
 2   salary  3 non-null      object
dtypes: object(1), str(2)
memory usage: 297.0+ bytes

In [12]:
df['city'].isna().sum()

np.int64(2)

In [14]:
df_city = df["city"].fillna("UNKNOWN")
df_city.head()

0    bangalore
1      UNKNOWN
2        delhi
3      kashmir
4      UNKNOWN
Name: city, dtype: str

In [16]:
df_new = df.copy()
df_new["city"] = df_city
df_new.head()

      name       city salary
0  vishwas  bangalore  20000
1      bob    UNKNOWN    NaN
2     john      delhi  30000
3     Rita    kashmir  20000
4    Smith    UNKNOWN   None

In [17]:
df_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   city    5 non-null      str
 2   salary  3 non-null      object
dtypes: object(1), str(2)
memory usage: 310.0+ bytes